CREATE TABLE IF NOT EXISTS pregunta(
  id bigint generated by default as identity, 
  category VARCHAR(255),
  question VARCHAR(255),
  options VARCHAR(255),
  answer INT,
  explanation VARCHAR(255),
  primary key (id)
);

CREATE TABLE IF NOT EXISTS categoria (
  id bigint generated by default as identity, 
  category VARCHAR(255),
  description VARCHAR(255),
  primary key (id)
);

INSERT INTO pregunta (category, question, options, answer, explanation)
VALUES
  ('Historia', '¿En qué año fue la Revolución Francesa?', '{"A. 1789", "B. 1804", "C. 1815", "D. 1830"}', 1, 'La Revolución Francesa comenzó en 1789 y tuvo un impacto significativo en la historia de Francia y Europa.'),
  ('Ciencia', '¿Cuál es el elemento químico más abundante en el universo?', '{"A. Hidrógeno", "B. Oxígeno", "C. Carbono", "D. Helio"}', 1, 'El hidrógeno es el elemento más abundante en el universo.'),  
  ('Cultura', '¿Cuál es el río más largo del mundo?', '{"A. Amazonas", "B. Nilo", "C. Yangtsé", "D. Misisipi"}', 2, 'El río Nilo es considerado el más largo del mundo, con una longitud aproximada de 6,650 kilómetros.'),
  ('Deportes', '¿En qué deporte se utiliza una raqueta?', '{"A. Tenis", "B. Fútbol", "C. Baloncesto", "D. Natación"}', 1, 'El tenis es un deporte en el que se utiliza una raqueta para golpear una pelota sobre una red.'),
  ('Arte', '¿Quién pintó La Mona Lisa marcelo?', '{"A. Leonardo da Vinci", "B. Pablo Picasso", "C. Vincent van Gogh", "D. Michelangelo"}', 1, 'La Mona Lisa fue pintada por Leonardo da Vinci, uno de los artistas más famosos del Renacimiento.'),
  ('Cine', '¿Cuál fue la primera película de la saga de Star Wars en ser lanzada?', '{"A. Star Wars: Episodio IV - Una nueva esperanza", "B. Star Wars: Episodio I - La amenaza fantasma", "C. Star Wars: Episodio VI - El retorno del Jedi", "D. Star Wars: Episodio V - El imperio contraataca"}', 1, 'La primera película de la saga de Star Wars en ser lanzada fue "Star Wars: Episodio IV - Una nueva esperanza" en 1977.');

  
INSERT INTO categoria (category, description)
VALUES
  ('Historia', 'Preguntas relacionadas con la Historia.'),
  ('Ciencia', 'Preguntas relacionadas con la Ciencia.'),  
  ('Cultura', 'Preguntas relacionadas con la Cultura.'),
  ('Deportes', 'Preguntas relacionadas con el Deporte.'),
  ('Arte', 'Preguntas relacionadas con el Arte.'),
  ('Cine', 'Preguntas relacionadas con el Cine.');
